services:
  spi3:
    image: debian:bookworm-slim
    user: root
    devices:
      - /dev/spidev0.0
    volumes:
      - .:/spi3
    command: >
      sh -c "apt update &&
             apt install -y python3 python3-spidev &&
             python3 /spi3/spi_service.py"
